### ISSUE TITLE
Pen-testing for DDoS

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#100]
If test will be successful it will be needed to fix vulnerabilities.

**Comment by chopin111** [comment]
Przeprowadziłem testy przy pomocy dwóch narzędzi  Low Orbit Ion Cannon oraz HULK (HTTP Unbearable Load King), żadne z nich nie przeszkodziło w pracy na dokumentach oraz wykonywaniu wszelakich operacji. Test zakończony sukcesem.
