### ISSUE TITLE
Python holds UTF-8 characters in 2 chars.

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#25]
To reproduce issue in python console type:
»> document = "Użytkownik"
»> for a in document:
... print a
... 
U
�
�
y
t
k
o
w
n
i
k

Every remove operation which deletes len(text) will remove additional characters if text have special UTF-8 characters. 

Possible solution, we can delete number of characters which will be sent by frontend if its possible to get correct len(text) in js with special UTF-8 characters. Now we are sending text to delete, not just number of chars.

**Comment by rutka** [comment]
If we want to have polish letters, we must write  u'Użytkownik' instead of  'Użytkownik' because of unicode.

It is not a problem for server, because data are send with this special unicode character.
