### ISSUE TITLE
Store new lines in document

### ISSUE THREAD

**Issue by Kelleth** [dbryla/WebTextEditor#28]
We could store new lines by inserting <br> on each enter pressed, but there would be problem with deleting them as <br> is 4 characters long

**Comment by dbryla** [comment]
It seems to like we need to change all data model. This issue is also assigned to @rutka @Kelleth :
We need to change data model, backend, frontend.

**Comment by Kelleth** [comment]
Done, as line is equivalent to text inside <p> </p> tags
