### ISSUE TITLE
Server side libraries integration

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#3]
Integration server with socket.io and mongoDB.

**Comment by rutka** [comment]
To run server with socketio execute bellow command:
sudo python manage.py runserver_socketio

Known issue with latest libraries:
https://github.com/stephenmcd/django-socketio/issues/63

Useful links to integrated technologies:
https://github.com/stephenmcd/django-socketio
http://docs.mongoengine.org/tutorial.html
