### ISSUE TITLE
Framework for front-end form

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#7]
Choose framework to create a simple form for editor.

**Comment by chopin111** [comment]
![front1](https://cloud.githubusercontent.com/assets/11414755/6769923/99c1cf14-d0af-11e4-89e9-4590efa5fdea.jpg)

Framework do paneli i przycisków - KickStart - http://www.99lime.com/elements/

**Comment by Kelleth** [comment]
Replaced div with an iframe
