### ISSUE TITLE
Technologies for import and export document

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#81]
Research. This issue is also assigned to @dbryla .

**Comment by dbryla** [comment]
To import document.<br>
First implement file upload: (It will be also used for Image upload)<br>
https://github.com/axelpale/minimal-django-file-upload-example <br>
Then implement backend to use:<br>
http://arsaperta.org/odftoolsen.html <br>
with xls schema: <br>
http://opendocumentfellowship.com/projects/odftools <br>
Then process all tags and save document to db.

**Comment by dbryla** [comment]
Added issues for import: #83, #84.

**Comment by rutka** [comment]
To export document to pdf

https://github.com/chrisglass/xhtml2pdf

Added issues for export #88 #89
