### ISSUE TITLE
Concurrent work bugs

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#93]
For example:
Pointer moves to start, after every concurrent change in document. (Possible workaround saving pointer position and moving it after setting changes.(Is it possible to be implemented?))

All minor bugs which won't be fixed, should be written somewhere.

**Comment by Kelleth** [comment]
Caret position and selection is now preserved on concurrent document update since https://github.com/dbryla/WebTextEditor/commit/53d7a74e976919217a605ba70e7bac748c65081c

**Comment by Kelleth** [comment]
https://github.com/dbryla/WebTextEditor/wiki/Bugs-related-to-text-editing
describes bugs related to document editing
