### ISSUE TITLE
Pen-testing for Broken Authentication and Session Management

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#98]
If test will be successful it will be needed to fix vulnerabilities.

**Comment by rutka** [comment]
Udało się przeprowadzić atak:
![screenshot - 11 06 2015 - 19 18 22](https://cloud.githubusercontent.com/assets/7187836/8119250/79c6fb38-1094-11e5-8887-b44784f96c41.png)

W celu zapobiegania takiemu atakowi zmieniliśmy sposób eksportu dokumentu. Zamiast wysyłać nazwę dokumentu oraz jego zawartość, wysyłamy id dokumentu i po stronie serwera pobieramy dokument z bazy danych. Następnie sprawdzamy czy dokument jest prywatny i czy zalogowany użytkownik ma uprawnienia do dokumentu.

![screenshot - 11 06 2015 - 23 55 39](https://cloud.githubusercontent.com/assets/7187836/8119397/7cad529c-1095-11e5-9cce-2c63a741b063.png)
